# Generated by Django 2.2 on 2021-04-20 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_mngt', '0002_auto_20210420_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock_mngt.Category'),
            preserve_default=False,
        ),
    ]
