# Generated by Django 2.2 on 2021-04-21 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_mngt', '0003_auto_20210420_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_csv',
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stock_mngt.Category'),
        ),
    ]
