# Generated by Django 2.2 on 2021-04-22 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_mngt', '0004_auto_20210421_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
